name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Indicates the location of the vcpkg as a Git submodule of the project repository.
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  # Tells vcpkg where binary packages are stored.
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
  # Use specific vcpkg version
  VCPKG_COMMIT_ID: '5568f110b509a9fd90711978a7cb76bae75bb092'

jobs:
  build:
    runs-on: ubuntu-22.04

    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y \
             gpg wget curl zip unzip tar git pkg-config \
             gcc-12 g++-12 ninja-build libstdc++-12-dev \
             clang-tidy cppcheck ccache

    - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
      run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
      shell: bash

    - name: Restore artifacts, or setup vcpkg
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '${{ env.VCPKG_COMMIT_ID }}'
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Run cmake
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-vcpkg-deb'
          testPreset: 'ninja-vcpkg-deb'
